### ISSUE TITLE
Phantom Macrophages

### ISSUE THREAD

**Issue by knappa** [NutritionalLungImmunity/lung-fungal-web#102]
![image](https://user-images.githubusercontent.com/4730938/108941675-7d1e4200-7623-11eb-8601-f3b432e63b0e.png)

You can't see it, but there is a dead macrophage selected in the middle of the cluster. It should either be non-selectable or visible.

**Comment by knappa** [comment]
Also, the phagosome display is non-informative. Perhaps length of non-null, non-neg1 entries instead?

**Comment by jbeezley** [comment]
The picking mechanism has odd behavior in general.  This logic is inside vtk js, so it will take some code spelunking to modify its behavior.  I fixed the null's in the panel anyway.
