### ISSUE TITLE
2d plots have x-axis labels duplicated

### ISSUE THREAD

**Issue by knappa** [NutritionalLungImmunity/lung-fungal-web#128]
![image](https://user-images.githubusercontent.com/4730938/112368907-f60bca80-8cb1-11eb-8342-be38b223d3f0.png)

Possible related issue which doesn't have a screenshot handy: Stepping forward/backward in time sometimes doesn't move the graph linearly. i.e. the position jumps back and forth.

**Comment by jbeezley** [comment]
I don't see this occurring on any of the simulations present in https://viewer.nutritionallungimmunity.org/.  The time step order is inferred from folder names and the time is provided by folder metadata.  I suspect something got mixed up in the generation of the output.  Perhaps an old output folder wasn't deleted correctly or there was a race condition in the creation.

**Comment by knappa** [comment]
I don't think that it is an old folder interfering, but I didn't check. These occasional glitches have only happened when the simulation is still running and, based on my memory, reloading resolves the issue. 

My guess for the back-and-forth problem was that the issue might occur when the time steps are loaded out of order.

**Comment by jbeezley** [comment]
I see.  That gives me a better idea where to look.
