### ISSUE TITLE
Unclear login button

### ISSUE THREAD

**Issue by knappa** [NutritionalLungImmunity/lung-fungal-web#75]
The login button is somewhat unclear and can be mistaken for a logout button. It is also not immediately clear to (pre-login) users why the "Run simulation" button is inactive. Should this be active for non-logged in users, but trigger the login process when clicked?

**Comment by jbeezley** [comment]
I don't know if #88 sufficiently addresses this issue.  The login button on the top right corner is actually the standard material login icon.  The logout icon is similar but shows an arrow pointing outside the box.

![login-logout](https://user-images.githubusercontent.com/31890/108401400-4e026d80-71ea-11eb-8501-3e49f4673ad7.png)

**Comment by knappa** [comment]
I think that #88 is sufficient for me. If anyone else becomes confused, we'll find out about it.

On the material icons: Obviously different when shown side by side, but separately and without careful inspection they look the same to me.
